### ISSUE TITLE
Please add option to power cycle on flash failure

### ISSUE THREAD

**Issue by Icesythe7** [ghidraninja/game-and-watch-flashloader#10]
on the cheap stlinks they seems to fail sometimes on flashing but after a power cycle I've never had a repeat failure of that chunk, something like this would be superb!

`    
# Try to flash 3 times, give up after that.
    COUNT=3
    for RETRY_COUNT in $(seq $COUNT); do
        if [[ $RETRY_COUNT -gt 1 ]]; then
            echo "Flashing chunk $i failed... power cycle unit and retry? (y/n)"
            read -n 1 -r
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                echo "Aborted."
                exit 1
            fi

            echo "Retry count $RETRY_COUNT/3"
        fi

        ${DIR}/flash.sh ${TMPFILE} ${ADDRESS_HEX} ${SIZE_HEX} ${ERASE} ${ERASE_BYTES} && break
    done`

oh also whatever file says "preparing chunk x..." the chunk is always 1 regardless of what chunk your on

**Comment by kbeckmann** [comment]
Thanks! dacb4f8cc477167ab064476bd24b80dac6db237a
