### ISSUE TITLE
Cann't do build 

### ISSUE THREAD

**Issue by wizz777** [ghidraninja/game-and-watch-flashloader#2]
Core/Src/flash.c: At top level:
Core/Src/flash.c:108:7: warning: conflicting types for 'OSPI_NOR_WriteEnable'
  108 | void  OSPI_NOR_WriteEnable(OSPI_HandleTypeDef *hospi)
      |       ^~~~~~~~~~~~~~~~~~~~
Core/Src/flash.c:101:5: note: previous implicit declaration of 'OSPI_NOR_WriteEnable' was here
  101 |     OSPI_NOR_WriteEnable(hospi);
      |     ^~~~~~~~~~~~~~~~~~~~
Core/Src/flash.c: In function 'OSPI_NOR_WriteEnable':
Core/Src/flash.c:112:11: warning: unused variable 'reg' [-Wunused-variable]
  112 |   uint8_t reg[2];
      |           ^~~
Core/Src/flash.c:111:27: warning: unused variable 'sConfig' [-Wunused-variable]
  111 |   OSPI_AutoPollingTypeDef sConfig;
      |                           ^~~~~~~
make: *** No rule to make target `build/startup_stm32h7b0xx.o', needed by `build/gw_base.elf'.  Stop.

**Comment by nezza** [comment]
Did you initialize the dependencies using STM32CubeMX? It's necessary to initialize the HAL etc :) we might need to add some documentation on that

**Comment by wizz777** [comment]
I just copied the catalog "Drivers" from another of my project and do "make". With "game-and-watch-base" and it's work for me.

**Comment by joksan** [comment]
What worked for me was to provide a symlink to both `STM32CubeH7/Drivers/` and `STM32CubeH7/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/startup_stm32h7b0xx.s` in the repository directory. Perhaps we should consider adding STM32CubeH7 as a submodule? or maybe provide a download script for that matter? I would recommend the former one, simply because of replicability reasons.

**Comment by wizz777** [comment]
> What worked for me was to provide a symlink to both `STM32CubeH7/Drivers/` and `STM32CubeH7/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc/startup_stm32h7b0xx.s` in the repository directory. Perhaps we should consider adding STM32CubeH7 as a submodule? or maybe provide a download script for that matter? I would recommend the former one, simply because of replicability reasons.

Thank you it works for me now.

**Comment by kbeckmann** [comment]
> Perhaps we should consider adding STM32CubeH7 as a submodule? or maybe provide a download script for that matter? 

@joksan yeah that would be nice! Having people download stm32cubemx and click a button is not ideal. Running a script or using submodules is much better, I agree. If you are up for it, would you like to take a look at this?

**Comment by joksan** [comment]
Sure! Let me see if I can find time for this tomorrow.
