### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by KsAmJ** [ghidraninja/game-and-watch-flashloader#3]
i can't build

`make
arm-none-eabi-gcc -c -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32H7B0xx -ICore/chocdoom -ICore/Inc -IDrivers/STM32H7xx_HAL_Driver/Inc -IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32H7xx/Include -IDrivers/CMSIS/Include -Og -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -O0 -MMD -MP -MF"build/flash.d" -Wa,-a,-ad,-alms=build/flash.lst Core/Src/flash.c -o build/flash.o
In file included from Core/Src/flash.c:1:
Core/Inc/flash.h:4:10: fatal error: stm32h7xx_hal.h: No such file or directory
    4 | #include "stm32h7xx_hal.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:254: build/flash.o] Error 1
`

**Comment by kbeckmann** [comment]
You have to open the project file in stm32cubemx and press the generate button in order to get all the HAL files.

**Comment by nezza** [comment]
It works, the repo has to be initialised with STM32cubemx as mentioned by Konrad.
